# Azure DevOps Pipeline for Clean Code Description Agent
trigger:
  branches:
    include:
      - main
      - develop

pr:
  branches:
    include:
      - main
      - develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: qodo-credentials

stages:
- stage: CleanCode
  displayName: 'Clean Code Review'
  jobs:
  - job: Review
    displayName: 'Run Clean Code Description Agent'
    steps:
    - task: Docker@2
      displayName: 'Run Qodo Clean Code Agent'
      inputs:
        command: 'run'
        image: 'qodoai/command:latest'
        arguments: >
          --prompt clean_code_description
          --agent-file path/to/agent.toml
          --key-value-pairs "target_branch=$(System.PullRequest.TargetBranch),severity_threshold=medium,focus_areas=docstrings,comments,naming,include_suggestions=true"
        envVars: |
          QODO_API_KEY=$(qodo-api-key)
          AZURE_TOKEN=$(System.AccessToken)
