# GitLab CI Configuration for Clean Code Description Agent
stages:
  - review

clean_code_review:
  stage: review
  image: qodoai/command:latest
  script:
    - |
      command \
        --prompt clean_code_description \
        --agent-file path/to/agent.toml \
        --key-value-pairs "target_branch=${CI_MERGE_REQUEST_TARGET_BRANCH_NAME:-main},severity_threshold=medium,focus_areas=docstrings,comments,naming,include_suggestions=true"
  variables:
    QODO_API_KEY: $QODO_API_KEY
    GITLAB_TOKEN: $CI_JOB_TOKEN
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
