# agent.toml

version = "1.0"
model = "claude-4-sonnet"

[commands.deploy-static]
description = "Deploy static Webflow export to AWS S3 and CloudFront with profile validation"
instructions = """
1. Ensure AWS CLI is installed (`aws --version`) and configured. Fail early if missing.
2. List AWS CLI profiles and use `profile` argument to select the active profile.
3. Create S3 bucket (if not exists) and set it for static hosting.
4. Sync the local folder to the S3 bucket.
5. Create or update a CloudFront distribution with Origin Access Identity/OAC.
6. Verify the OAC is configured correctly.
7. Invalidate CloudFront cache for updated files.
8. Test the deployment by visiting the CloudFront distribution domain.
"""

arguments = [
  { name = "folder", type = "string", required = true, description = "Directory of Webflow-exported static files" },
  { name = "bucket", type = "string", required = false, description = "Target S3 bucket name" },
  { name = "profile", type = "string", required = false, description = "AWS CLI profile to use" }
]

available_tools = ["filesystem", "desktop-commander"]

execution_strategy = "act"

output_schema = """
{
  "type": "object",
  "properties": {
    "profileInUse": { "type": "string", "description": "The AWS CLI profile in use" },
    "bucket": { "type": "string", "description": "The S3 bucket name" },
    "distributionId": { "type": "string", "description": "The CloudFront distribution ID" },
    "distributionDomain": { "type": "string", "description": "The CloudFront distribution domain" },
    "invalidatedPaths": { "type": "array", "items": { "type": "string" }, "description": "The paths invalidated" },
    "syncSummary": { "type": "string", "description": "The summary of the sync operation" }
  },
  "required": ["profileInUse", "bucket", "distributionId", "distributionDomain", "invalidatedPaths", "syncSummary"]
}
"""

