# Azure DevOps Pipeline for Code Review Agent
trigger:
  branches:
    include:
      - main
      - develop

pr:
  branches:
    include:
      - main
      - develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: qodo-credentials

stages:
- stage: CodeReview
  displayName: 'Code Review'
  jobs:
  - job: Review
    displayName: 'Run Code Review'
    steps:
    - task: Docker@2
      displayName: 'Run Code Review Agent'
      inputs:
        command: 'run'
        image: 'qodoai/command:latest'
        arguments: >
          --prompt code-review
          --agent-file path/to/agent.toml
          --key-value-pairs "target_branch=$(System.PullRequest.TargetBranch),severity_threshold=medium,focus_areas=security,performance,include_suggestions=true"
        envVars: |
          QODO_API_KEY=$(qodo-api-key)
          AZURE_TOKEN=$(System.AccessToken)